### ISSUE TITLE
How do I add new EH Clause while rewriting the IL

### ISSUE THREAD

**Issue by hkesharia** [microsoftarchive/clrprofiler#2]
Hi,

I am not sure whether this is the right forum to ask this question, I apologize in advance if it's the wrong place. I am working on the project where I need to instrument some method at runtime. I am stuck here and looking for the solution.

My requirement to instrument a given method, extract input arguments and return value. By any chance, if there is an exception, I need the exception detail as well. I need to call .Net code after fetching the requirement data from the method. 

To achieve this, I am using IL Rewrite code base to inject the epilogue and prologue in a method. I have modified the 'ilrewriter' code and getting a callback with input arguments for the prologue and return value for the epilogue in the .Net. So far so good. 

Now, I am trying to handle exception scenario. To do so, I am trying to inject try/catch block by adding new EHClause 'ilrewriter' class. In the catch block, I will callback .Net code and then just rethrow. Of course, I am appending the new instructions that are needed for catch block as well for final return. Along with that, I am also updating all the return OpCode with Leave.  I am appending below instruction in my method - 

`	//     Replace return with following 
	//     ...
	     stloc.0
	     leave.s <int>
	//     ...
	//     Append following block at the end of a method
	//     ...
	     pop
	     ldarg.0 (load 'this')
	     call CallOnException
	     rethrow
	     ldloc.0
	     ret
`
Somehow, it's not working as expected. Can anyone please guide me how do I add try/catch that covers entire method?

**Comment by terrajobst** [comment]
This repo is archived and not actively maintained. Consider failing an issue in https://github.com/dotnet/runtime.
