### ISSUE TITLE
Errors when compiling [VS-2019]

### ISSUE THREAD

**Issue by DynConcepts** [microsoftarchive/clrprofiler#4]
They are all of the form.....

Error (active)	E0167	argument of type "void (*)(FunctionIDOrClientID functionIDOrClientID)" is incompatible with parameter of type "FunctionTailcall3 *"	ProfilerOBJ	C:\Users\david.corbin\source\repos\clrprofiler-master\CLRProfiler\profilerOBJ\ProfilerCallback.cpp	1015

**Comment by terrajobst** [comment]
This repo is archived. Consider filing an issue in https://github.com/dotnet/runtime.
